### ISSUE TITLE
Kanban board setup - Review

### ISSUE THREAD

**Issue by ram1117** [roniy68/catalog-of-my-things#18]
Hi , 

we are a team of three members - @roniy68 @Lancelot-SO @ram1117 

Team member 1 - Ram Kumar Karuppusamy
Team member 2 - Ahmed Hasan Rony
Team member 3 - Felix Sowah

project link - https://github.com/roniy68/catalog-of-my-things/projects/1

We have created the Kanban cards accordingly and have assigned tasks to each team member. Please review the board setup and provide feedback.

**Comment by prolajumokeoni** [comment]
Hi @Team
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Cards added for Team members 1 & 2



## Required Changes ♻️

- [ ] Kindly add Cards for team member 3 as this is a team of 3 👍🏿 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ram1117** [comment]
@prolajumokeoni Hi Priscilla. we do have added cards for third member

![image](https://user-images.githubusercontent.com/116718155/233962231-60f8aab7-ad0c-4af3-9fc6-4ae0e86118f0.png)

**Comment by prolajumokeoni** [comment]
> @prolajumokeoni Hi Priscilla. we do have added cards for third member
> 
> ![image](https://user-images.githubusercontent.com/116718155/233962231-60f8aab7-ad0c-4af3-9fc6-4ae0e86118f0.png)

I think i missed it, Please resubmit it would be approved, I apologise for the confusion

**Comment by Nemwel-Boniface** [comment]
## Hello @ram1117 , @Lancelot-SO , and @roniy68   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request and I have double-checked it and according to when the cards were created, it is clear that the cards for the third student were already there and @prolajumokeoni  seems to have missed that.

However, I can see that your project has already been approved :rocket: 

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!
